### ISSUE TITLE
Self XSS in Code To Hack Our Account's 

### ISSUE THREAD

**Issue by ghost** [CaptainEgypt/SubscribeToAllH1#1]
بسم الله الرحمن الرحيم 

يستخدم هذا الكاتب " الاخ زمبي هيلب 54 " احد الاكواد الخبيثة لكي يدعس حسابتنا عن طريق الهندسة الاجتماعية 

ويرجي من الادمن حذف الاداة و شكرأ !

**Comment by Zombiehelp54** [comment]
تم دعس الملايين .. هيخهخهو 

Mohamed is just kidding btw :D
